@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

LAYOUT_TOP_DOWN()

Person(clienteUser, "Cliente", "Quem usa a aplicação")
Person(salaoUser, "Salão", "Quem tem o salão de beleza")
System(sistema, "Sistema de Agendamento", "Sistema para agendamento de serviços de beleza")

System_Ext(mapsExternal, "Google Maps", "Serviço de mapas para localização do salão")
System_Ext(stripeExternal, "Stripe", "Serviço de pagamento para processar transações")
System_Ext(emailExternal, "Email Service", "Serviço de email para notificações")
System_Ext(loginExternal, "Google Auth", "Serviço de autenticação Google para usuários")

Rel(clienteUser, sistema, "Usa para agendar serviços")
Rel(salaoUser, sistema, "Usa para gerenciar agendamentos e serviços")
Rel(sistema, mapsExternal, "Usa para mostrar localização do salão")
Rel(sistema, stripeExternal, "Usa para processar pagamentos")
Rel(sistema, emailExternal, "Usa para enviar notificações de agendamento")
Rel(sistema, loginExternal, "Usa para autenticar usuários")


@enduml